fix: use html-webpack-plugin-for-multihtml to increase compilation speed
weex-templates/webpack pull request #5
Opened 2018-09-03 02:35 UTC by hacke2

fix: https://github.com/weexteam/weex-toolkit/issues/315

If we have many vue component. It will so slow when a minor change.

The reason is that every component of weex will generate a page, and each time HtmlWebpackPlugin is modified, it will analyze whether there is a file to modify.

For example, there are 30 files in my project.

Before optimization:

![image](https://user-images.githubusercontent.com/6399899/44964756-be5a9d00-af64-11e8-8bb0-012d675202fa.png)

After optimization:

![image](https://user-images.githubusercontent.com/6399899/44964786-daf6d500-af64-11e8-82c5-a1a677df859e.png)

Speed increased by 95%!!! 🎉

2018-09-03 02:42 UTC, erha19 requested changes
The `html-webpack-plugin-for-multihtml` module can't be found in the package.json, it will cause an error about `cannot find module 'html-webpack-plugin-for-multihtml'`.

2018-09-03 02:43 UTC, erha19 commented on template/package.json
> +    "hard-source-webpack-plugin": "^0.12.0",
What's this module used for?

2018-09-03 02:47 UTC, hacke2 commented on template/package.json
> +    "hard-source-webpack-plugin": "^0.12.0",
my fault, fixed

2018-09-03 02:51 UTC, erha19 approved these changes

2018-09-03 02:51 UTC, merged

2018-09-18 08:38 UTC, weiweiwei256 commented
@hacke2   Is There any details for using html-webpack-plugin-fro-multihtml?  Demo code.  
I have same issue.